---
# test tasks file for how to upgrade BIOS
  
- hosts: servers
  remote_user: root
  roles:
    - role: 'Huawei.server-upgrade'
      command: 'auto-upgrade'
      # the driver list to be upgraded
      outbandFW: 
        - ['FW-Bios', '8.82']